const actionTypes = {
    CHARACTERS_LOADING:'CHARACTERS_LOADING',
    LOAD_CHARACTERS:'LOAD_CHARACTERS',
    LOAD_CHARACTERS_ERROR:'LOAD_CHARACTERS_ERROR',

    SET_CHARACTER_LOADING:'SET_CHARACTER_LOADING',
    LOAD_CHARACTERS_QUOTES:'LOAD_CHARACTERS_QUOTES',
    LOAD_CHARACTERS_QUOTES_ERROR:'LOAD_CHARACTERS_QUOTES_ERROR'
}

export default actionTypes;