const actionTypes = {
    CHARACTERS_LOADING:'CHARACTERS_LOADING',
    LOAD_CHARACTERS:'LOAD_CHARACTERS',
    LOAD_CHARACTERS_ERROR:'LOAD_CHARACTERS_ERROR',

    LOAD_CHARACTER_LOADING:'LOAD_CHARACTER_LOADING',
    LOAD_CHARACTER_QUOTES_BY_NAME:'LOAD_CHARACTER_QUOTES_BY_NAME',
    LOAD_CHARACTER_QUOTES_ERROR:'LOAD_CHARACTER_QUOTES_ERROR',
}

export default actionTypes;